# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_win64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_win64)
  PML_config = debug_win64
endif
ifeq ($(config),debug_linux)
  PML_config = debug_linux
endif
ifeq ($(config),release_win64)
  PML_config = release_win64
endif
ifeq ($(config),release_linux)
  PML_config = release_linux
endif

PROJECTS := PML

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

PML:
ifneq (,$(PML_config))
	@echo "==== Building PML ($(PML_config)) ===="
	@${MAKE} --no-print-directory -C . -f PML.make config=$(PML_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f PML.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_win64"
	@echo "  debug_linux"
	@echo "  release_win64"
	@echo "  release_linux"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   PML"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"